Repository nuxt/typescript, pull requests merged in 2020-03, with the labels that each got.

#308 docs(ja): fix translation
  docs/ja/guide/lint.md
Labels: documentation, translation

#305 Add type declaration file tip in the documentation
  docs/guide/setup.md
Labels: documentation

#317 feat: support nuxt 2.12
  packages/types/app/vue.d.ts
Labels: feature, types

#322 Fix testing of fork-ts-checker-webpack-plugin v4
  packages/typescript-build/package.json
  packages/typescript-build/test/module.test.ts
  yarn.lock
Labels: dependencies
