Repository nuxt/typescript, pull requests merged in 2021-01, with the labels that each got.

#476 corrected cookbook link
  docs/content/en/guide/setup.md
Labels: documentation

#472 Updating and fixing the Portuguese translation
  docs/content/pt/cookbook/components.md
  docs/content/pt/cookbook/configuration.md
  docs/content/pt/cookbook/middlewares.md
  docs/content/pt/cookbook/modules.md
  docs/content/pt/cookbook/plugins.md
  docs/content/pt/cookbook/server-middlewares.md
  docs/content/pt/cookbook/store.md
  docs/content/pt/examples/class-api/minimal.md
  docs/content/pt/examples/composition-api/minimal.md
  docs/content/pt/examples/options-api/minimal.md
  docs/content/pt/guide/introduction.md
  docs/content/pt/guide/lint.md
  docs/content/pt/guide/runtime.md
  docs/content/pt/guide/setup.md
  docs/content/pt/index.md
  docs/nuxt.config.js
Labels: documentation, translation

#475 fix(examples): add `vue-class-component` dependency
  examples/class-api/minimal/package.json
Labels: examples, fix

#478 chore(deps): upgrade dependencies (includes TypeScript 4.1)
  .eslintignore
  .github/workflows/test.yml
  docs/components/global/InjectCode.vue
  docs/package.json
  docs/plugins/vue-tabs.js
  docs/yarn.lock
  jest.config.js
  package.json
  packages/typescript-build/package.json
  packages/typescript-build/src/index.ts
  packages/typescript-runtime/package.json
  yarn.lock
Labels: dependencies
